Update README.md
DaveeHorvath/ascension pull request #100
Opened 2024-12-30 06:10 UTC by taoramo

Correct port 8443 in Readme.

2024-12-30 12:05 UTC, madfcat commented
Why do we need this change? I always use port 443.
For me, it's always `https://localhost` without explicit port.

I would also suggest to change this part (in `index.html`) to relative path
```
        const popup = window.open(
          "https://localhost:8443/api/oauth/redirect", // This should match your Django URL pattern
          "42 Authorization"
        );
```
        
like this: `"/api/oauth/redirect"`

2024-12-30 13:19 UTC, taoramo commented
> Why do we need this change? I always use port 443. For me, it's always `https://localhost` without explicit port.
1) we want to run this on school machines and you need sudo for 443.
2) oauth callback is currently setup for 8443.
3) there's no reason to not use 8443.
> 
> I would also suggest to change this part (in `index.html`) to relative path
> 
> ```
>         const popup = window.open(
>           "https://localhost:8443/api/oauth/redirect", // This should match your Django URL pattern
>           "42 Authorization"
>         );
> ```
> 
> like this: `"/api/oauth/redirect"`
This makes sense.

2024-12-30 13:41 UTC, madfcat commented
@taoramo I think I get your point. We need to change 443 to 8443 in nginx.conf and docker-compose.yml too.
I guess I could never make it run with 8443 on my machine.
And I have never run this project on the school computer.
I will give it a try now.

2024-12-30 13:47 UTC, madfcat requested changes

2024-12-30 13:47 UTC, madfcat commented on README.md
>  ### Game
We do not use game.html at all. Our project implements SPA.
The file `game.html` should be removed completely. I think it is some legacy stuff. Therefore, we do not even need this Game part in our README.md

2024-12-30 13:52 UTC, madfcat commented
> @taoramo I think I get your point. We need to change 443 to 8443 in nginx.conf and docker-compose.yml too. I guess I could never make it run with 8443 on my machine. And I have never run this project on the school computer. I will give it a try now.

@dnapi @nikkxll @taoramo
I successfully ran it with 8443 port. Should we stick to the port 8443 and 443 and just change it finally to 8443 in nginx.conf and docker-compose.yml?

2024-12-31 10:46 UTC, madfcat approved these changes

2024-12-31 10:46 UTC, dnapi commented
I have also run it on 8443 on my laptop. both option should work for me

2024-12-31 10:46 UTC, merged