Nikkxll/profile new features
DaveeHorvath/ascension pull request #80
Opened 2024-12-18 16:26 UTC by nikkxll

- Added new features to the profile (pass + username change, some stats)
- Added winRate and totalMatches params to the tournament and single game lobbies
- Minor changes and fixes

2024-12-18 20:45 UTC, madfcat requested changes

2024-12-18 20:45 UTC, madfcat commented on frontend/src/js/profileSettings.js
> +        (player) => player.username != "ai_player"
```suggestion
        (player) => (player.username != "ai_player" && player.id != userId)
```

2024-12-18 21:36 UTC, nikkxll commented on frontend/src/js/profileSettings.js
> +        (player) => player.username != "ai_player"
Changed
Thx!

2024-12-18 23:58 UTC, madfcat commented
Updating `username` when user has no `displayName`, does not update it in the lobby and in the recent matches.

Also, consider adding username to the profile, so a user can see the initial username. And update it after changes.

No consistency between the button hovers. I guess it can be added later if needed.

2024-12-19 16:03 UTC, nikkxll commented
Added features and fixes in accordance with the @madfcat last comment

2024-12-19 16:34 UTC, madfcat commented
`username` input field should be emptied after successful update.
At the moment, it still has the last value after update.

2024-12-19 16:39 UTC, madfcat commented
Please, update styles like this (styles.css line 159):
```
input[type="file"] {
	color: transparent;
	width: 100%;
  }
  
input[type="file"]::file-selector-button {
	display: block;
	margin: 0 auto;
	border-radius: 5px;
	border: unset;
	cursor: pointer;
	transition: background-color 0.3s;
}
input[type="file"]::file-selector-button:hover {
	background-color: #000000;
	color: rgba(255, 255, 255, 0.5);
}
```

It will make the "Choose file" button have the same style.

2024-12-19 17:01 UTC, nikkxll commented
Updated

2024-12-19 17:04 UTC, madfcat approved these changes
Looking good!

2024-12-19 17:04 UTC, merged